services:
  - type: web
    name: checkin
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn checkin.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: checkin-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0